### ISSUE TITLE
import binaries fails

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/arche-ingest#3]
running `repo-ingestion@pandorfer/import_binaries.php < input` (which is a copy of [import_binary_sample.php](https://github.com/acdh-oeaw/arche-ingest/blob/master/import_binary_sample.php)) fails
* if `parentResourceId` is set 

> Uncaught Error: Call to undefined function GuzzleHttp\Psr7\mimetype_from_filename() in /ARCHE/vendor/acdh-oeaw/arche-lib-ingest/src/acdhOeaw/arche/lib/ingest/schema/File.php:173

* if `$parentResourceId = ''` 
> PHP Fatal error:  Uncaught Error: Typed property acdhOeaw\arche\lib\ingest\Indexer::$parent must not be accessed before initialization in /ARCHE/vendor/acdh-oeaw/arche-lib-ingest/src/acdhOeaw/arche/lib/ingest/Indexer.php:602

**Comment by zozlak** [comment]
The first one means guzzlehttp/psr7 v2 has been released, the second one is PHP8-related stuff.

Fixes should be delivered today.

**Comment by zozlak** [comment]
Resolved in arche-lib-ingest
