### ISSUE TITLE
Number of instances is confusing

### ISSUE THREAD

**Issue by bellerophons-pegasus** [acdh-oeaw/arche-ingest#4]
Ingest scripts need a number as an argument to indicate which instance should be used.

Currently, 1 is for the development instance, 2 for the production instance and 3 for curation.

For me, this is confusing, as I would expect the highest number to also be the 'highest/best' instance (aka production)
Is it, without much hassle, possible to switch this to:
1 is for the development instance, 2 for the curation instance and 3 for the production instance?

Otherwise I'll just have to get used to it.

**Comment by zozlak** [comment]
It's a matter of the order in the local config (the `repositories` property in the `acdh_resources/ARCHE/config.yaml` file).

Adjusted it already the way you suggested.
