### ISSUE TITLE
Undefined variable $rc in delete_resource_sample

### ISSUE THREAD

**Issue by bellerophons-pegasus** [acdh-oeaw/arche-ingest#5]
I tried out the latest version of `delete_resource_sample.php` with some resource to be deleted (only modified `$resourceId` in line 6).

This is the error I get:
`PHP Warning:  Undefined variable $rc in /ARCHE/staging/troesmis_6787/scriptFiles/delete_resource.php on line 49
PHP Fatal error:  Uncaught Error: Call to a member function getConstant() on null in /ARCHE/staging/troesmis_6787/scriptFiles/delete_resource.php:49
Stack trace:
#0 {main}
  thrown in /ARCHE/staging/troesmis_6787/scriptFiles/delete_resource.php on line 49
`

**Comment by zozlak** [comment]
Fixed by 877d9897445f15ec8fbc159fab34392f1e45acd3 (you can just remove this line)
